<ul id="menu" class="page-sidebar-menu">
    <!-- DASHBOARD -->
    <li {!! (Request::is('dashboard') ? 'class="active"' : '') !!}>
      <a href="{{ route('investor-dashboard') }}">
        <i class="livicon" data-name="home" data-size="18" data-c="#418BCA" data-hc="#418BCA"
          data-loop="true"></i>
        <span class="title">Dashboard</span>
      </a>
    </li>

    <!-- MY PROJECT -->
    <li {!! (Request::is('groups') || Request::is('groups/create') || Request::is('groups/*') ? 'class="active"' : '') !!}>
      <a href="{{ URL::to('owner/show-project') }}">
        <i class="livicon" data-name="barchart" data-size="18" data-c="#418BCA" data-hc="#418BCA"
          data-loop="true"></i>
        <span class="title">My Project</span>
      </a>
    </li>

    <!-- All EMPLOYEES -->
    <li {!! (Request::is('groups') || Request::is('groups/create') || Request::is('groups/*') ? 'class="active"' : '') !!}>
      <a href="{{ URL::to('owner/all-employees') }}">
        <i class="livicon" data-name="users" data-size="18" data-c="#418BCA" data-hc="#418BCA"
          data-loop="true"></i>
        <span class="title">Employee</span>
      </a>
    </li>

    <!-- ALL PRODUCTS -->
    <li {!! (Request::is('groups') || Request::is('groups/create') || Request::is('groups/*') ? 'class="active"' : '') !!}>
      <a href="#">
          <i class="livicon" data-name="shopping-cart" data-size="18" data-c="#418BCA" data-hc="#418BCA"
             data-loop="true"></i>
          <span class="title">Product</span>
          <span class="fa arrow"></span>
      </a>
      <ul class="sub-menu">
          <li {!! (Request::is('groups') ? 'class="active" id="active"' : '') !!}>
              <a href="{{ URL::to('owner/product') }}">
                  <i class="fa fa-angle-double-right"></i>
                  All Products
              </a>
          </li>
      </ul>
      <ul class="sub-menu">
          <li {!! (Request::is('groups') ? 'class="active" id="active"' : '') !!}>
              <a href="{{ URL::to('owner/product/create') }}">
                  <i class="fa fa-angle-double-right"></i>
                  Add New Product
              </a>
          </li>
      </ul>
  </li>

    <!-- Menus generated by CRUD generator -->
    @include('layouts/menu')
</ul>
